Description of parseGeneRule
Home > src > PC-FBA > parseGeneRule.m
parseGeneRule
PURPOSE
This function parse model.rules{i} into a array of all logical
SYNOPSIS
function enzymeString = parseGeneRule(ruleString)
DESCRIPTION
 This function parse model.rules{i} into a array of all logical
 combinations of genes, each cluster separated by ";". This is a very
 important function in PC-model implementation.
 USAGE:
   enzymeString = parseGeneRule(ruleString)
 INPUTS:
   ruleString: The string from model.rules{i}
 OUTPUTS:
   enzymeString: Output string formatted
 EXAMPLE:
   enzymeString = parseGeneRule('(((x(105)&x(107))&x(103))|(x(105)&x(107))|(x(105)&x(102))|(x(104)&x(106)))')
 NOTE:
   This function is capable of handling various modes of rule annotations.
   However, mis-annotation of brackets (especially missing left brackets)
   tends to make this function throw error. The user may need to manually
   fix certain entries in model.rules and please always check if rules are
   parsed correctly after using.
 .. AUTHOR: - Herbert Yao, Dec 2023
CROSS-REFERENCE INFORMATION
This function calls:
parseGeneRule This function parse model.rules{i} into a array of all logical
This function is called by:
parseGeneRule This function parse model.rules{i} into a array of all logical
pcModel (MAIN) Construct a PC-model from M-model