Description of pcModel
Home > src > PC-FBA > pcModel.m
pcModel
PURPOSE
(MAIN) Construct a PC-model from M-model
SYNOPSIS
function [constraintedModel,fullProtein,fullCplx,C_matrix,K_matrix,fullProteinMM] = pcModel(model,fasta,maxWeightFrac)
DESCRIPTION
 (MAIN) Construct a PC-model from M-model
 A function that produce a protein constrainted M-model from a base
 M-model and protein sequence data.
 USAGE:
   new_model = proteinConstraintModel(model,'Paeruginosa.fasta',150);
 INPUTS:
   model: A functional COBRA model struct with the field 'genes'
   fasta: The file name of a proteome fasta file containing geneID
          (same set of ID as model.genes) as header and respective protein
          sequence in one-letter symbol.
          Alternatively, you can put an estimated average protein length
          (avg # of amino acid per protein) if you don't have access to
          fasta. The modelling accuracy will be compromised.
 OPTIONAL INPUTS:
   maxWeightFrac: A double denotes the maximum weight fraction of total
                  protein components, in mg/gDW. Default = 150mg/gDW
 OUTPUTS:
   constraintedModel: A m-model with proteomic constraint
   fullProtein:       A full list of proteins added to model.mets
   fullEnzyme:        A full list of enzymes added to model.mets
   C_matrix:          A matrix which related to enzyme formation
   K_matrix:          A matrix of enzyme's catalyzing coefficient (k_eff)
   fullProteinMM:     Molar mass of each protein in fullProtein
 REQUIREMENTS:
   MATLAB with Bioinformatics and Deep Learning Toolbox installed
   Configured CobraToolbox with at least one capable solver
 Important Note:
   New_model.mets will contain all proteins and enzymes (protein
   complexes). Each protein and enzyme will have an exchange rxn and a
   enzyme formation rxn. Fluxes of these reactions are not real flux, but
   representing their concentration in nmol/gDW. Therefore, the
   concentration of protein_i is -v_{EX_protein_i} and the concentration
   of enzyme_j is v_{EX_enzyme_j} = v_{enzymeForm_enzyme_j}
CROSS-REFERENCE INFORMATION
This function calls:
calcProteinMM The function returns the molar mass of a given protein sequence.
findProteinSeq The function returns a protein sequence from fasta file. If the ID is not
parseGeneRule This function parse model.rules{i} into a array of all possible enzymes
This function is called by: